### ISSUE TITLE
Segfault error when calling ./user

### ISSUE THREAD

**Issue by folleah** [BitObscuro/Obscuro#1]
I trying command:
```
./user 0200000001b6613cc68a051ef39bfee3a49c0f8e78f07fa6971ce720427c5990c03f7ae84f010000006b483045022100e13b2863649570796c3a2db9ffa72fe37964be7d3c0cbb4aa06a7904501c5766022060d1519c94612164eacc7319760b00f282723deb748e2891ddeb296aaf3ac0120121038c2d5f7099ccab7d5971a00292bed4996f45a6e56d94fa3373b0d1562cd4d466feffffff02201d9a00000000001976a91447baf5a9d0abc13f1ad7098429fba0225114238c88acf0cf4c29010000001976a914ddeede29817ed83878d1b7d2a166b254c8351a1788ac65000000 cR3RU1y4gRVR6AsY9qQihckKJ4VVWU8PPmYRtVy1tfcE6kHZF3Vf cUxtCbTxVsbUTUApK6sDWXpHNZoW2YmsGDbErvB9FDcJPFH9kTnv
```

But this not execute with segfault:
```
Core was generated by `./user 0200000001b6613cc68a051ef39bfee3a49c0f8e78f07fa6971ce720427c5990c03f7ae8'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd867119f01 in ?? ()
```

SGX successfully installed and running (1.6). Bicoin Core version 0.15.
System: `Linux foll 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by muoitranduc** [comment]
The prototype was tested with Bitcoin Core 0.13 and Ubuntu 14.04, unfortunately.

**Comment by muoitranduc** [comment]
If it is not too late, the guide has been updated.
Please try with Bitcoin Core 0.13.1, although I think there won't be much different.

About your bugs, I think it is because the bitcoin daemon hasn't been started yet.
