### ISSUE TITLE
Does the project use libsecp256k1 from the directory or does it use a precompiled libsecp256k1.a

### ISSUE THREAD

**Issue by hybridNeo** [BitObscuro/Obscuro#2]
Hi I wanted to build this project on my system hence I wanted to know how to compile the secp256k1 for sgx, it looks like it's using a precompiled libsecp256k1.a

**Comment by hybridNeo** [comment]
Figured out that it is using a pre-compiled library, hence closing this.

**Comment by muoitranduc** [comment]
Yep, the library used inside SGX is pre-complied.
