### ISSUE TITLE
Error building Obscuro

### ISSUE THREAD

**Issue by fairaschain** [BitObscuro/Obscuro#3]
Hi, I have installed sgx sdk as mentioned in the readme and when I am trying to build Obscuro using 'make' command I am getting following error:

error: `ocall_getpwnam_r': invalid 'string' attribute - `pwd' is not char pointer.
Makefile:138: recipe for target 'App/MyEnclave_u.c' failed
make: *** [App/MyEnclave_u.c] Error 255

**Comment by muoitranduc** [comment]
What is your Ubuntu version?

**Comment by fairaschain** [comment]
Ubuntu 16.04

**Comment by muoitranduc** [comment]
Unfortunately, this prototype was tested with Ubuntu 14.04.
Let me check if I can make it work with a more recent OS.

**Comment by muoitranduc** [comment]
@fairaschain I have updated the guide with more details, you may try to follow the steps again.

**Comment by fairaschain** [comment]
Thank you so much. I will try and get back to you if I face any other problem.

**Comment by vishnu1911** [comment]
I am trying to install it on my ubuntu 18.04 version and I am facing the same issue. Can you help with this?

**Comment by muoitranduc** [comment]
> I am trying to install it on my ubuntu 18.04 version and I am facing the same issue. Can you help with this?

I think the SGX SDK for Linux version 1.8 (which we use in this prototype) cannot work on Ubuntu 18.04.

**Comment by vishnu1911** [comment]
Is there any way I can modify the code such that it works on 18.04?

**Comment by muoitranduc** [comment]
> Is there any way I can modify the code such that it works on 18.04?

The earliest version of SGX SDK for Linux that supports Ubuntu 18.04 is v2.3, which is significantly different from the version 1.8.
Our prototype will need a major upgrade to be compatible with Ubuntu 18.04, unfortunately.

**Comment by vishnu1911** [comment]
When i make the project, I a getting the following error. The operating system is Ubuntu 14.04 i386 32 bit
/usr/bin/ld: i386:x86-64 architecture of input file `App/vrfcert_u.o' is incompatible with i386 output
I am not able to figure out the error. Can you please help

**Comment by muoitranduc** [comment]
Probably you have to install Ubuntu 64-bit or make your Ubuntu works with 64-bit applications.

**Comment by vishnu1911** [comment]
Thank you, got that figured. But original problem in this query i.e. 
error: ocall_getpwnam_r': invalid 'string' attribute - pwd' is not char pointer.
Makefile:138: recipe for target 'App/MyEnclave_u.c' failed
make: *** [App/MyEnclave_u.c] Error 255

The above error still persists and I am not able to find out the fault. I am using ubuntu 14.04 64 bit version. Hence ubuntu version should not be problem right?

**Comment by muoitranduc** [comment]
Certainly, Ubuntu version is not a problem in this situation. Few people have independently tested with Ubuntu 14.04, VirtualBox, etc.. 

Please make sure that you have done *exactly* the instructions.  
Probably you can try to "make clean", re-install everything from scratch. 

Sorry I cannot be more helpful. I cannot reproduce the errors so all I can do is to guess. I can also provide a link include an OVA file including everything ready to run.

**Comment by vishnu1911** [comment]
Hi, I am getting the same error even if I try to reinstall the entire project. Can you please provide the OVA file as mentioned in the above comment

**Comment by muoitranduc** [comment]
Did you face any compiling errors before making the project? 
In other words, did you see any problem when installing the Intel SGX SDK?

I'm preparing the OVA file and updating the README file.

**Comment by vishnu1911** [comment]
Sorry, I have not noticed this earlier. But I have an error while running dependency commands.
There is no such file or directory isgx.ko while running this sudo cp isgx.ko "/lib/modules/"`uname -r`"/kernel/drivers/intel/sgx"

**Comment by muoitranduc** [comment]
Oh this is an easy fix. You have to compile the Intel SGX Driver by entering "make" command.
I updated the README file. Thanks for the bug report. You will be able to compile the project now.
OVA file will be available soon. I need to find somewhere to post it.

**Comment by vishnu1911** [comment]
Thank you for the fix! Its compiling now!!
